//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinesiologiaMiramar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Orden = new HashSet<Orden>();
        }
    
        public int PK_Paciente { get; set; }
        public string Documento { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FecNac { get; set; }
        public string Calle { get; set; }
        public string Localidad { get; set; }
        public string CodPostal { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string Email { get; set; }
        public Nullable<int> FK_Os { get; set; }
        public string OsAfiliado { get; set; }
        public string OsPlan { get; set; }
        public string OsIva { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual ObraSocial ObraSocial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Orden { get; set; }
    }
}
