//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinesiologiaMiramar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int PK_Turno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> TurnoHora { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> FK_Orden { get; set; }
        public Nullable<bool> Presente { get; set; }
    
        public virtual Orden Orden { get; set; }
    }
}
